### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by nielsvanvelzen** [frysztak/orpington-news#121]
Hi there, I'm currently looking into options for a self-hosted RSS aggregator and discovered Orpington. It seems to fit my needs but I don't have any services using Postgres so it feels a bit overboard to run an instance for a tool that won't have much data (in my specific case that is.)

Are there any plans to add SQLite support?

**Comment by frysztak** [comment]
hey, unfortunately no, I don't ever see supporting databases other than Postgres.

I'm currently in the process of rewriting backend into Rust and rethinking how certain aspects of the app work - and that actually ties the app even closer to Postgres-specific features.

if that's any help, I have a [docker-compose template](https://github.com/frysztak/orpington-news/blob/dev/docker-compose.template.yml), which should make setting Postgres up nice and easy
