### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by vk2r** [frysztak/orpington-news#140]
I have tried lifting the Docker Compose file in the Readme and unfortunately, at the time of implementing it in Portainer, it did not work.

My server is a RPi4 and it gives me the following error: 
![imagen](https://user-images.githubusercontent.com/1544900/232973037-0a91aca3-5da0-4ecc-80e3-6963bb25a065.png)

**Comment by frysztak** [comment]
I think it's kind of expected - ARM64 image was dropped in [v0.12.0](https://github.com/frysztak/orpington-news/releases/tag/0.12.0). though I am a little surprised Docker doesn't guard against downloading images for another CPU architecture

**Comment by vk2r** [comment]
I understand.
How can I solve this? Will it help to download an older version?

**Comment by frysztak** [comment]
I'll try to prepare new version with ARM64 support this week

**Comment by vk2r** [comment]
Thank you very much

**Comment by frysztak** [comment]
@vk2r I gave it a try and it's rather tricky. I can't get it to work at this time, but I'll move it up on my to-do list

**Comment by frysztak** [comment]
Released in v0.12.4 :tada:
