### ISSUE TITLE
[bug] Error when renaming my feed

### ISSUE THREAD

**Issue by vk2r** [frysztak/orpington-news#145]
I have imported the OPML file from Feedly and when trying to rename the feed, unfortunately I get this error.

`Json deserialize error: missing field 'url' at line 1 column 94`

Apparently there are some fields that Feedly does not give to the file and it would be good to add them, in case the OPML file does not have them.

<img width="406" alt="bug" src="https://user-images.githubusercontent.com/1544900/235374678-dfa2de01-d303-462b-b7cc-bfbc32b19bb2.png">

**Comment by frysztak** [comment]
issue was with renaming Collections that didn't have URL set. this is now fixed in v0.12.5. thanks for reporting
