### ISSUE TITLE
Support for reddit rss feeds ("." in feed url)

### ISSUE THREAD

**Issue by milksteakjellybeans** [frysztak/orpington-news#149]
Not sure if this is a feature request or a "bug" but reddit exposes rss feeds with ".rss" in the url.

When adding a feed in orpington-news (Version: 0.12.4 Git commit: 802b0102), for example, "https://reddit.com/r/debian/new/.rss" an error under the url entry appears as "Please enter valid URL", and the "Add" button is disabled.

But, if I do an OPML import with similar urls, everything seems to work fine.

Example OPML excerpt:

`<outline title="reddit" text="reddit">
<outline type="rss" htmlUrl="https://reddit.com/r/unifi_versions/new" title="UniFi Firmware Versions" xmlUrl="https://reddit.com/r/unifi_versions/new/.rss" text="UniFi Firmware Versions" />
</outline>
`

More about reddit rss:
https://www.reddit.com/wiki/rss/

Even more info:
https://danielmiessler.com/p/reddit-rss-functionality-explained/

**Comment by frysztak** [comment]
this is definitely a bug - I remember testing with Reddit RSS but I wasn't aware of this particular URL form - I used e.g. `https://reddit.com/r/debian.rss`. anyway, thanks for report - this is now fixed in v0.12.5

**Comment by milksteakjellybeans** [comment]
Hmm, running the latest from docker (Version: 0.12.5 Git commit: 470b0d78), instead of getting a validation error during "Verify URL" via Add Feed, I get:

"Error
Invalid RSS/Atom feed."

This happens for both URLs of the form,
https://reddit.com/r/debian/new/.rss
but also for URLs like you suggested,
https://reddit.com/r/debian.rss

This could be more of an issue on the reddit side, I don't know.

OPML import still working fine for the same URL

**Comment by frysztak** [comment]
yes, you're correct. I suspect it's got to do with Reddit's rate limiting. I'll have to look into it some more

**Comment by frysztak** [comment]
so basically Reddit became more stringent and it now requires `User-Agent` header to be present on requests, otherwise it returns `429 Too Many Requests`. Orpington News was setting its `User-Agent`, but not for all requests. this is now fixed. I'll cut a new release later today

**Comment by frysztak** [comment]
fixed in v0.12.6
