### ISSUE TITLE
Question: Is it possible to make a feed's parent folder manually within the orpington-news web ui?

### ISSUE THREAD

**Issue by milksteakjellybeans** [frysztak/orpington-news#160]
In the videos / screenshots on the projects main page it appears that you can have a feed's parent be a folder-like entity without it's own feed.  It looks like I can achieve that through OLML import, but is there a way to make a non-feed parent with orpington-news web ui?  I seem to be missing it if so.

I tried adding a new parent in the "Parent" field while adding a new feed, but that seems to only accept existing feeds/parents.
I also tried the organize option in the settings, but there doesn't seem to be an option to make a parent there.

If there is no option outside of OPML import that's fine, I can certainly use that, but I figured I'd ask in case I was missing how to make these within the UI.

Thank you

**Comment by frysztak** [comment]
yes, there is a way to do that, in fact that's mostly how I organize feeds in my private instance

> I tried adding a new parent in the "Parent" field while adding a new feed, but that seems to only accept existing feeds/parents.

that's the first way - you need to create a parent without URL, and then edit every feed to set its parent. for a lot of feeds this can be tedious, and that's where the second option comes in:

> I also tried the organize option in the settings, but there doesn't seem to be an option to make a parent there.

you just need to drag what you want to be a child under the future parent, like in this video:

https://user-images.githubusercontent.com/217806/195674330-62585a3f-f430-42a0-aa77-5aa576752137.mp4

it can be a little janky, but it should work

let me know how it goes!

**Comment by milksteakjellybeans** [comment]
> you need to create a parent without URL, and then edit every feed to set its parent.

This appears to no longer be functional.  I tried with 0.12.6 and 0.12.5 and it did not work.  This does work in 0.12.4 though, so I guess it's a knock-on bug from the URL validation changes.

Here's what 0.12.6/0.12.5 looks like:
![image](https://github.com/frysztak/orpington-news/assets/106365477/3466abc8-d29b-4cd5-b8ec-cfabfef53669)

**Comment by frysztak** [comment]
yes you're right, I just released v0.12.7 - should be all good :crossed_fingers:
