### ISSUE TITLE
run a development environment

### ISSUE THREAD

**Issue by yawks** [frysztak/orpington-news#54]
Hello,

Nice project, I would be interesting to understand how it works.
Could you indicate how to build a development environment? Maybe on the README page?
Thanks!

**Comment by frysztak** [comment]
hey @yawks, thanks a lot! you can now find instructions on `dev` branch: https://github.com/frysztak/orpington-news/tree/dev#development-quick-start

in case of any trouble, let me know!

**Comment by yawks** [comment]
Thank you, it worked.
Juste one thing, I used my existing postgres instance, and the user I created needed to have superuser role for init.sql file.

**Comment by frysztak** [comment]
that's good to know, although it shouldn't be a problem when running Postgres within a Docker container, since [created user has superuser role](https://github.com/docker-library/docs/blob/master/postgres/README.md#postgres_user)
