### ISSUE TITLE
Can't sign up with user profile pic defined

### ISSUE THREAD

**Issue by henryxrl** [frysztak/orpington-news#80]
It seems I can't sign up if the profile pic is defined. I get this error message:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/7662954/200161008-9d9c8f9d-19f7-49bf-b5c7-03c5c0c635ef.png">

After I remove the profile pic, I'm able to sign up. However, I can't log in... The button spins a bit but nothing happens. On the other hand, if I input incorrect user or password, it shows a notification.

**Comment by frysztak** [comment]
I assume you're running the app in a Docker container?

> However, I can't log in... The button spins a bit but nothing happens.

that bit is very strange. it would be helpful to see API responses - could you open browser's devtools and post the errors here?

also running
```sh
$ docker exec -it orpington-news pm2 logs --lines 50 api
```
might reveal some more

**Comment by henryxrl** [comment]
I was able to successfully sign in by assigning the docker URL to the URL I filled in for one of the environment variables via reverse proxy. Now everything works.

**Comment by frysztak** [comment]
great, thanks for letting me know :+1:
